name: branchUpdate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update_feature_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
      - name: Merge main into development
        run: |
          git checkout development
          git pull origin develop
          git rebase master
          git push origin development

      #- name: Push changes
      #  run: git push origin development
